### ISSUE TITLE
Make the Red Hat update certificates capability idempotent.

### ISSUE THREAD

**Issue by williambailey** [williambailey/vagrant-ca-certificates#1]
The [Red Hat update certificates capability](/williambailey/vagrant-ca-certificates/blob/cbc583829c386582055bf3318c3d944e8a3640c4/lib/vagrant-ca-certificates/cap/redhat/update_certificates.rb) is not currently idempotent.

**Comment by johnbellone** [comment]
This should be complete once the 1.0.0 release is ready.
