### ISSUE TITLE
1.0.1 on rubygems.org doesn't match release on github

### ISSUE THREAD

**Issue by kkumykov** [williambailey/vagrant-ca-certificates#16]
The 1.0.1 release on rubygems.org seems to not match the 1.0.1 release on github, namely it doesn't seem to include at least the path fix for windows hosts. (Compare lib/vagrant-ca-certificates/action/install_certificates.rb in the gem and in the github release)

**Comment by johnbellone** [comment]
Sorry about that. 1.0.2 released.
