### ISSUE TITLE
vagrant-ca-certificates does not exist on rubygems

### ISSUE THREAD

**Issue by ermaker** [williambailey/vagrant-ca-certificates#6]
There is no result for http://rubygems.org/search?utf8=%E2%9C%93&query=vagrant-ca-certificates

So this fails.
```
$ vagrant plugin install vagrant-ca-certificates
```

If you have any idea for this, please let me know.

Thank you for reading this issue.

**Comment by johnbellone** [comment]
I am waiting to squash out existing problems first. This will happen soon.
